services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network
    ports:
      - 5432:5432

  backend:
    image: ${BACKEND_IMAGE}
    container_name: backend
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_ACCESS_TOKEN_SECRET: ${JWT_ACCESS_TOKEN_SECRET}
      JWT_REFRESH_TOKEN_SECRET: ${JWT_REFRESH_TOKEN_SECRET}
      JWT_USER_CRETE_SECRET: ${JWT_USER_CRETE_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      EMAIL_SERVICE: ${EMAIL_SERVICE}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    depends_on:
      - postgres
    networks:
      - backend-network
    ports:
      - 41679:3001

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge
